lib/merchant_repository.rb, test/merchant_repository_test.rb
Updates:
*Create new id method
*Start of Create new Merchant method
Pending:
*update(id, attributes) - update the Merchant instance with the corresponding id with the provided attributes. Only the merchant’s name attribute can be updated.
*delete(id)- delete the Merchant instance with the corresponding id
=> Merchant repo 4

Gemfile, lib/merchant_repository.rb, test/merchant_repository_test.rb
Updates:
*Finished tested create new merchant method
Pending:
*update(id, attributes) - update the Merchant instance with the corresponding id with the provided attributes. Only the merchant’s name attribute can be updated.
*delete(id) - delete the Merchant instance with the corresponding id
=> Merchant repo 5

lib/merchant_repository.rb, test/merchant_repository_test.rb
Updates:
*Draft update method
Pending:
*delete(id)- delete the Merchant instance with the corresponding id
=> Merchant repo update merchant

lib/merchant_repository.rb, test/merchant_repository_test.rb, test/test_helper.rb
Update:
*Finalize merchant repo class and test suite
=> Merchant repo final

lib/file_loader.rb, lib/item_repository.rb, lib/merchant_repository.rb, lib/sales_engine.rb, test/merchant_repository_test.rb, test/sales_engine_test.rb, test/test_helper.rb
very very minor clean up for linter
=> Sales engine 1

lib/item_repository.rb, lib/merchant_repository.rb, test/item_repository_test.rb, test/merchant_repository_test.rb
moving from file reading to mock data
=> complete rework of testing strategy t

lib/item_repository.rb, test/item_repository_test.rb
Finished:
*all - returns an array of all known Item instances
*find_by_id(id) - returns either nil or an instance of Item with a matching ID
*find_by_name(name) - returns either nil or an instance of Item having done a case insensitive search
*delete(id) - delete the Item instance with the corresponding id
*find_all_with_description(description) - returns either [] or instances of Item where the supplied string appears in the item description (case insensitive)
Update:
*find_all_by_price(price) - returns either [] or instances of Item where the supplied price exactly matches
Pending:
*find_all_by_price_in_range(range) - returns either [] or instances of Item where the supplied price is in the supplied range (a single Ruby range instance is passed in)
*find_all_by_merchant_id(merchant_id) …
=> Item repo description

lib/item_repository.rb, test/item_repository_test.rb, test/merchant_repository_test.rb, updates.md
Fixes merchant repo test to move away from pulling in csv data to using mock data
=> fix merchant_repo tests

lib/item_repository.rb, lib/merchant_repository.rb, test/item_repository_test.rb
Finished:
*all - returns an array of all known Item instances
*find_by_id(id) - returns either nil or an instance of Item with a matching ID
*find_by_name(name) - returns either nil or an instance of Item having done a case insensitive search
*delete(id) - delete the Item instance with the corresponding id
*find_all_with_description(description) - returns either [] or instances of Item where the supplied string appears in the item description (case insensitive)
*update(id, attributes) - update the Item instance with the corresponding id with the provided attributes. Only the item’s name, desription, and unit_price attributes can be updated. This method will also change the items updated_at attribute to the current time.
Update:
Finished item update method
Pending:
=> Item repo update item

lib/item.rb, lib/item_repository.rb
=> Item repo wtf

lib/item_repository.rb, lib/merchant_repository.rb, test/item_repository_test.rb, test/merchant_repository_test.rb
add/improve update item/merchant functionality to account for nil passing through
=> Sales engine start

lib/item_repository.rb, lib/merchant_repository.rb, lib/repository_module.rb
Moves update functionality out of item and merchant repo classes and into the repo module
=> Repository assistant

lib/item_repository.rb, lib/merchant_repository.rb, lib/repository_assistant.rb, test/item_repository_test.rb, test/merchant_repository_test.rb, test/sales_engine_test.rb
Updated the name of the repository module to RepositoryAssistant, in it's file and throughout
=> update repository module to repository assistant

lib/sales_analyst.rb, lib/sales_engine.rb, test/sales_analyst_test.rb, test/sales_engine_test.rb
Finished:
*sales_analyst = sales_engine.analyst
*sales_analyst.average_items_per_merchant # => 2.88
Pending:
Iteration 1
*sales_analyst.average_items_per_merchant_standard_deviation # => 3.26
*sales_analyst.merchants_with_high_item_count # => [merchant, merchant, merchant]
*sales_analyst.average_item_price_for_merchant(12334159) # => BigDecimal
*sales_analyst.average_average_price_per_merchant # => BigDecimal
*sales_analyst.golden_items # => [<item>, <item>, <item>, <item>]
=> Sales analyst 1

lib/invoice.rb, lib/sales_analyst.rb, test/invoice_test.rb, test/sales_analyst_test.rb
Setting up invoice class and test suite
=> Invoice setup

lib/invoice_repository.rb, lib/item_repository.rb, lib/merchant_repository.rb, lib/repository_assistant.rb, test/invoice_repository_test.rb, test/merchant_repository_test.rb
Invoice and Invoice Repo are complete
=> Ivoice repo

lib/invoice_item.rb, test/invoice_item_test.rb
Adds final functionality for Invoice Item and Invoice Item Test classes
=> Invoice item

test/invoice_item_test.rb, test/invoice_test.rb, test/merchant_repository_test.rb, test/sales_engine_test.rb
Hound CI and Simplecov suggested refactors implemented
=> add minor refactors for Hound CI

lib/invoice_item_repository.rb, lib/repository_assistant.rb, test/invoice_item_repository_test.rb
Finalize Invoice Item Repo class and test class
=> Invoice item repo

lib/invoice_repository.rb, test/invoice_repository_test.rb
add tiny refactorings to invoice and invoice repo classes
=> add small refactorings for drier code

lib/invoice.rb, lib/invoice_item.rb, lib/item.rb, lib/merchant.rb, lib/sales_engine.rb, lib/transaction.rb, test/sales_engine_test.rb, test/transaction_test.rb
Adds small refactorings to merchant, item, invoice, invoice item and transaction files for better continuity of styling across files
=> add refactorings for file continuity

lib/transaction.rb, test/transaction_test.rb
Add finalized transaction and test classes
=> Transaction

lib/invoice_item_repository.rb, lib/repository_assistant.rb, lib/transaction_repository.rb, test/transaction_repository_test.rb
=> Transaction repo

lib/customer_repository.rb, lib/repository_assistant.rb, test/customer_repository_test.rb
Add final version of customer repo and unit test suite
=> Customer repo

lib/sales_analyst.rb, test/sales_analyst_test.rb
method provides hash with merchant Id as keys and their respective items as an array for the values.
=> working group by method for sales_analyst

test/invoice_repository_test.rb
add update to find by status test to reflect status coming in as a symbol
=> update invoice status to symbol

lib/standard_deviation.rb
add mock data directory with smaller data sets for all repositories
add standard deviation module
add new file paths for sales analyst test suite
=> initial commit for standard deviation module

lib/sales_analyst.rb, lib/standard_deviation.rb, test/sales_analyst_test.rb, updates.md
Finished:
*sales_analyst.average_invoices_per_merchant # => 10.49
*sales_analyst.average_items_per_merchant_standard_deviation # => 3.26
*sales_analyst.average_invoices_per_merchant_standard_deviation # => 3.29
*sales_analyst.top_merchants_by_invoice_count # => [merchant, merchant, merchant]
*sales_analyst.bottom_merchants_by_invoice_count # => [merchant, merchant, merchant]
Pending:
Iteraltion 2
*sales_analyst.top_days_by_invoice_count # => ["Sunday", "Saturday"]
*sales_analyst.invoice_status(:pending) # => 29.55
sales_analyst.invoice_status(:shipped) # => 56.95
sales_analyst.invoice_status(:returned) # => 13.5
=> Std deviation module

lib/sales_analyst.rb, test/sales_analyst_test.rb, updates.md
Finished:
*sales_analyst.average_invoices_per_merchant # => 10.49
*sales_analyst.average_items_per_merchant_standard_deviation # => 3.26
*sales_analyst.average_invoices_per_merchant_standard_deviation # => 3.29
*sales_analyst.top_merchants_by_invoice_count # => [merchant, merchant, merchant]
*sales_analyst.bottom_merchants_by_invoice_count # => [merchant, merchant, merchant]
*sales_analyst.top_days_by_invoice_count # => ["Sunday", "Saturday"]
Pending:
Iteraltion 2
*sales_analyst.invoice_status(:pending) # => 29.55
sales_analyst.invoice_status(:shipped) # => 56.95
sales_analyst.invoice_status(:returned) # => 13.5
=> Top days by invoice count

lib/sales_analyst.rb, test/sales_analyst_test.rb, updates.md
Finished: Iteraltion 2
*sales_analyst.average_invoices_per_merchant # => 10.49
*sales_analyst.average_items_per_merchant_standard_deviation # => 3.26
*sales_analyst.average_invoices_per_merchant_standard_deviation # => 3.29
*sales_analyst.top_merchants_by_invoice_count # => [merchant, merchant, merchant]
*sales_analyst.bottom_merchants_by_invoice_count # => [merchant, merchant, merchant]
*sales_analyst.top_days_by_invoice_count # => ["Sunday", "Saturday"]
*sales_analyst.invoice_status(:pending) # => 29.55
sales_analyst.invoice_status(:shipped) # => 56.95
sales_analyst.invoice_status(:returned) # => 13.5
Complete
Pending:
No pending actions
=> Invoice status

test/sales_analyst_test.rb, updates.md
add tiny house keeping for extra lines, notes, skips and tracking log updates
=> add general house keeping for update tracking log

lib/repository_assistant.rb, test/customer_repository_test.rb, test/invoice_item_test.rb, test/transaction_repository_test.rb, test/transaction_test.rb
clean up repo unit tests to align with changes made to classes in accordance with spec harness requirements
=> add updates to all repository tests 

test/invoice_repository_test.rb, test/sales_engine_test.rb
add additional unit tests to bring test coverage up to 100%
=> Sales engine test coverage

lib/merchant_analytics.rb, lib/sales_analyst.rb, test/sales_analyst_test.rb, updates.md
bundle exec rspec spec/iteration_4_spec.rb
Completed Iterations: 0, 1, 2, 3
Iteration 4 in progress
Finished:
*sales_analyst.total_revenue_by_date(date) #=> $$
*sales_analyst.top_revenue_earners(x) #=> [merchant, merchant, merchant, merchant, merchant]
Pending:
Iteration 4: Merchant Analytics
*sales_analyst.top_revenue_earners #=> [merchant * 20]
*sales_analyst.merchants_with_pending_invoices #=> [merchant, merchant, merchant]
*sales_analyst.merchants_with_only_one_item #=> [merchant, merchant, merchant]
*sales_analyst.merchants_with_only_one_item_registered_in_month("Month name") #=> [merchant, merchant, merchant]
*sales_analyst.revenue_by_merchant(merchant_id) #=> $
*sales_analyst.most_sold_item_for_merchant(merchant_id) #=> [item] (in terms of quantity sold) …
=> Iteration 4 1

lib/merchant_analytics.rb, lib/sales_analyst.rb, lib/standard_deviation.rb, test/sales_analyst_test.rb, updates.md
bundle exec rspec spec/iteration_4_spec.rb
Completed Iterations: 0, 1, 2, 3
Iteration 4 in progress
Finished:
*sales_analyst.total_revenue_by_date(date) #=> $$
*sales_analyst.revenue_by_merchant(merchant_id) #=> $
*sales_analyst.top_revenue_earners(x) #=> [merchant, merchant, merchant, merchant, merchant]
*sales_analyst.top_revenue_earners #=> [merchant * 20]
*sales_analyst.merchants_with_only_one_item #=> [merchant, merchant, merchant]
*sales_analyst.merchants_with_pending_invoices #=> [merchant, merchant, merchant]
Pending:
Iteration 4: Merchant Analytics
*sales_analyst.merchants_with_only_one_item_registered_in_month("Month name") #=> [merchant, merchant, merchant]
*sales_analyst.most_sold_item_for_merchant(merchant_id) #=> [item] (in terms of quantity sold) …
=> Top revenue earners

lib/business_intelligence.rb, lib/merchant_analytics.rb, lib/sales_analyst.rb
Add business intelligence module to separate out  Iteration 2 methods from Iteration 4 methods
=> Business intelligence

lib/sales_analyst.rb, test/sales_analyst_test.rb
fix find_merchants_by_revenue; passes spec harness now
=> quick fix for refactored method name
